#define ID_TOGGLE_DOCK                  192
#define ID_APPLY_FILTER                 100000
#define ID_CONTROLS                      101000
#define IDD_LIVEPRESETS                 190
#define IDD_LIVEPRESET                  191
#define IDD_SETTINGS                    193
#define IDD_CONFIRM                 194
#define IDD_CONTROLVIEW                 195
#define IDD_ABOUT                       196
#define IDC_ADD                         1090
#define IDC_REMOVE                      1093
#define IDC_ADD2                        1091
#define IDC_REMOVE2                     1092
#define IDC_LIST                        1095
#define IDC_EDIT                        1096
#define IDC_SAVE                        1100
#define IDC_UPDATE                      1107
#define IDC_DESC                        1114
#define IDC_NAME                        1138
#define IDC_CANCEL                      1306
#define IDC_SETTINGS                    1359
#define IDC_ID                          1360
#define IDC_TREE                        1361
#define IDC_UNDO                        1362
#define IDC_RECALL_ACTIVE_PLUGINPRESETS 1363
#define IDC_RECALL_MUTED_PLUGINS        1364
#define IDC_RECALL                      1365
#define IDC_RECALL_ACTIVE_PRESETS       1366
#define IDC_HIDE_MUTED_TRACKS           1367
#define IDC_TOGGLETRACKVISIBILITY       1368
#define IDC_COMBO                       1369
#define IDC_LABEL1                      1370
#define IDC_TAB                         1371
#define IDC_ASSIGNINFO                  1372
